### ISSUE TITLE
worker panics on querying stf state

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-worker#20]
when getting `meetup_index_time_and_location` the worker panics

```
Jun 25 22:22:26 devsgx03 encointer-worker[8861]: [2020-06-25T20:22:26Z DEBUG substratee_worker_enclave] Scanning block 288938 for relevant xt
Jun 25 22:22:26 devsgx03 encointer-worker[8861]: [2020-06-25T20:22:26Z DEBUG substratee_worker_enclave] Restored ECC pubkey:
Jun 25 22:22:26 devsgx03 encointer-worker[8861]: [2020-06-25T20:22:26Z DEBUG substratee_worker_enclave::io::light_validation] backup chain relay state
Jun 25 22:22:26 devsgx03 encointer-worker[8861]: [2020-06-25T20:22:26Z DEBUG substratee_worker_enclave::io::light_validation] Seal Chain Relay State. Current state: LightValidationTest { num_relays: 1, tracked_relays: {1: RelayInfo { last_finalized_block_header_number: 288938, current_validator_set: [(<wasm:stripped>, 1), (<wasm:stripped>, 1)], current_validator_set_id: 0 amount of transaction in tx_inclusion_queue: 13 }} }
Jun 25 22:22:26 devsgx03 encointer-worker[8861]: [2020-06-25T20:22:26Z INFO  encointer_worker::ws_server] [WS Server] Forwarding message to worker event loop: Binary([2, 1, 2, 80, 80, 51, 80, 149, 90, 254, 138, 16, 125, 111, 17, 93, 194, 83, 235, 93, 117, 163, 254, 55, 169, 11, 55, 61, 178, 108, 193, 46, 60, 102, 97, 98, 182, 151, 213, 154, 65, 236, 213, 237, 250, 10, 159, 138, 38, 145, 62, 190, 132, 212, 248, 14, 220, 28, 147, 75, 231, 182, 249, 246, 51, 176, 95, 114, 103, 73, 55, 179, 62, 61, 48, 177, 225, 18, 236, 238, 24, 92, 170, 148, 64, 97, 121, 2, 183, 169, 82, 162, 96, 188, 222, 192, 102, 99, 88, 44, 134, 79, 198, 206, 96, 233, 40, 98, 42, 71, 70, 26, 84, 247, 96, 122, 220, 120, 23, 116, 84, 56, 78, 36, 248, 223, 4, 159, 174, 174, 130, 98, 182, 151, 213, 154, 65, 236, 213, 237, 250, 10, 159, 138, 38, 145, 62, 190, 132, 212, 248, 14, 220, 28, 147, 75, 231, 182, 249, 246, 51, 176, 95])
Jun 25 22:22:30 devsgx03 encointer-worker[8861]: Synced 288939 blocks out of 288939 finalized blocks
Jun 25 22:22:30 devsgx03 encointer-worker[8861]: [2020-06-25T20:22:30Z INFO  encointer_worker::ws_server]      [WS Server] Got message 'WsServerRequest { client: Sender { token: Token(0), channel: mio::channel::SyncSender<Command>, connection_id: 0 }, request: StfState(trusted(TrustedGetterSigned { getter: meetup_index_time_and_location(50503350955afe8a107d6f115dc253eb5d75a3fe37a90b373db26cc12e3c6661 (5Dt1Wg85...), 0x62b697d59a41ecd5edfa0a9f8a26913ebe84d4f80edc1c934be7b6f9f633b05f), signature: AnySignature(0x72674937b33e3d30b1e112ecee185caa9440617902b7a952a260bcdec06663582c864fc6ce60e928622a47461a54f7607adc78177454384e24f8df049faeae82) }), 0x62b697d59a41ecd5edfa0a9f8a26913ebe84d4f80edc1c934be7b6f9f633b05f) }'.
Jun 25 22:22:30 devsgx03 encointer-worker[8861]: [2020-06-25T20:22:30Z INFO  encointer_worker::ws_server]      [WS Server] Query state
Jun 25 22:22:30 devsgx03 encointer-worker[8861]: [2020-06-25T20:22:30Z DEBUG substratee_worker_enclave] verifying signature of TrustedGetterSigned
Jun 25 22:22:30 devsgx03 encointer-worker[8861]: [2020-06-25T20:22:30Z DEBUG substratee_worker_enclave::state] State loaded from ./shards/7eLSZLSMShw4ju9GvuMmoVgeZxZimtvsGTSvLEdvcRqQ/state.bin with size 8509B, deserializing...
Jun 25 22:22:32 devsgx03 encointer-worker[8861]: [2020-06-25T20:22:32Z DEBUG substratee_worker_enclave] Update STF storage!
Jun 25 22:22:32 devsgx03 encointer-worker[8861]: [2020-06-25T20:22:32Z INFO  substratee_stf::sgx] No specific storage updates needed for getter. Returning those for on block: trusted(TrustedGetterSigned { getter: meetup_index_time_and_location(, 0x62b697d59a41ecd5edfa0a9f8a26913ebe84d4f80edc1c934be7b6f9f633b05f), signature: <wasm:stripped> })
Jun 25 22:22:32 devsgx03 encointer-worker[8861]: [2020-06-25T20:22:32Z DEBUG substratee_worker_enclave] calling into STF to get state
Jun 25 22:22:32 devsgx03 encointer-worker[8861]: thread '<unnamed>' panicked at 'index out of bounds: the len is 9 but the index is 18446744073709551615', /home/abrenzikofer/.cargo/git/checkouts/pallets-8ad78cde507fea12/f60169a/ceremonies/src/lib.rs:559:18
Jun 25 22:22:32 devsgx03 encointer-worker[8861]: note: Call backtrace::enable_backtrace with 'PrintFormat::Short/Full' for a backtrace.
Jun 25 22:22:32 devsgx03 encointer-worker[8861]: fatal runtime error: failed to initiate panic, error 5
```

worker version 0.6.9

**Comment by brenzi** [comment]
in the above, the MRENCLAVE set by the client was wrong (not checked for getters)
with the correct MRENCLAVE we get the same:

```
Jun 25 22:45:46 devsgx03 encointer-worker[3686]: [2020-06-25T20:45:46Z INFO  encointer_worker::ws_server]      [WS Server] Got message 'WsServerRequest { client: Sender { token: Token(0), channel: mio::channel::SyncSender<Command>, connection_id: 2 }, request: StfState(t
rusted(TrustedGetterSigned { getter: meetup_index_time_and_location(50503350955afe8a107d6f115dc253eb5d75a3fe37a90b373db26cc12e3c6661 (5Dt1Wg85...), 0x62b697d59a41ecd5edfa0a9f8a26913ebe84d4f80edc1c934be7b6f9f633b05f), signature: AnySignature(0x881f2f9deb2d9bcad234f74b4605
913b35e010b4a85d3f20d82de8e2e249160104626f00a036ab16c2fcc50bd4ab6cf40e0acca841aad1027a14af2cf0335286) }), 0x62b697d59a41ecd5edfa0a9f8a26913ebe84d4f80edc1c934be7b6f9f633b05f) }'.
Jun 25 22:45:46 devsgx03 encointer-worker[3686]: [2020-06-25T20:45:46Z INFO  encointer_worker::ws_server]      [WS Server] Query state
Jun 25 22:45:46 devsgx03 encointer-worker[3686]: [2020-06-25T20:45:46Z DEBUG substratee_worker_enclave] verifying signature of TrustedGetterSigned
Jun 25 22:45:46 devsgx03 encointer-worker[3686]: [2020-06-25T20:45:46Z DEBUG substratee_worker_enclave::state] State loaded from ./shards/7eLSZLSMShw4ju9GvuMmoVgeZxZimtvsGTSvLEdvcRqQ/state.bin with size 8547B, deserializing...
Jun 25 22:45:48 devsgx03 encointer-worker[3686]: [2020-06-25T20:45:48Z DEBUG substratee_worker_enclave] Update STF storage!
Jun 25 22:45:48 devsgx03 encointer-worker[3686]: [2020-06-25T20:45:48Z INFO  substratee_stf::sgx] No specific storage updates needed for getter. Returning those for on block: trusted(TrustedGetterSigned { getter: meetup_index_time_and_location(, 0x62b697d59a41ecd5edfa0a9
f8a26913ebe84d4f80edc1c934be7b6f9f633b05f), signature: <wasm:stripped> })
Jun 25 22:45:48 devsgx03 encointer-worker[3686]: [2020-06-25T20:45:48Z DEBUG substratee_worker_enclave] calling into STF to get state
Jun 25 22:45:48 devsgx03 encointer-worker[3686]: thread '<unnamed>' panicked at 'index out of bounds: the len is 9 but the index is 18446744073709551615', /home/abrenzikofer/.cargo/git/checkouts/pallets-8ad78cde507fea12/9765159/ceremonies/src/lib.rs:559:18
Jun 25 22:45:48 devsgx03 encointer-worker[3686]: note: Call backtrace::enable_backtrace with 'PrintFormat::Short/Full' for a backtrace.
Jun 25 22:45:48 devsgx03 encointer-worker[3686]: fatal runtime error: failed to initiate panic, error 5
```

**Comment by brenzi** [comment]
the problem seems to be that the getter accesses on-chain storage which isn't updated:
EncointerCurrencies Locations:

https://github.com/encointer/pallets/blob/9765159a7fa55dd69f1bc164d0b8d560d0413f0d/ceremonies/src/lib.rs#L557

Because this is a double map, it's not trivial to update

**Comment by brenzi** [comment]
not true, locations is updated:
https://github.com/encointer/encointer-worker/blob/53e9ef984086824c8b867b06cc6c5c3675011779/stf/src/sgx.rs#L266

and the index out of bound may never happen because it is checked:
https://github.com/encointer/pallets/blob/9765159a7fa55dd69f1bc164d0b8d560d0413f0d/ceremonies/src/lib.rs#L558

**Comment by brenzi** [comment]
if meetup_idx is zero the index will wrap around because of the -1. easy to fix in pallet
