### ISSUE TITLE
client panics when encrypting payload on a CPU without RDRAND instruction

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-worker#27]
client v0.6.10

when running through cantillon tutorial, at 
```
nctr trusted register-participant $account1 --mrenclave $MRENCLAVE --shard $cid
```
I get
```
[2020-08-27T18:58:05Z INFO  substratee_worker_api] [+] Got RSA public key of enclave
[2020-08-27T18:58:05Z DEBUG substratee_worker_api]   enclave RSA pubkey = Rsa3072KeyPair: { n:431FED2CF6849569CD1F94CAAF214B3C3A5CA625F9EC9950380580016873B93A572304B76F1D2612397D688BC7F11E8473623834B1D836E4CE6F30CDC0A32772779AD6CB30B9ABD3E0191BD4326AD265E1B6A98040C70BAB83752E839565681AAD8A44CA4D6316A7C0178DABFAC97A246F01489A43A4B7423FAA2AD76851C141C3B47916C7BF4DD22FDBBACFAF52F8700260A2CB4DE0C95750BC93BF4A8FAF93127B9E3C984CCAF7675810795173C0F479811C6184888EBAB4080904F0028C533C817C661AC81513C7D7FB606D6DC666201A122D396CF072BAC19E897D179CD4EBC06B8568F7A12B84E0B487340C6D44C727C9B9FC67D467C183C2463267366D060861EBF1A7F7FC8E9753117B01EA11CDC9999F7191E0913FE31323FCF9B10222307E4C04EDAF61B020FAD4081B6EF647AC0FFA97C391A562540682DE55C20694986ECBD7EC895684819D3E620976817A4765904248045BE272A138D0B6010CC4C244BB496F22F00FBE85B2AF3F0929C20AA701549980B7917793F0C4606690, e:01000001 }
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Unavailable, msg: "the instruction is not supported", cause: None }', /home/abrenzikofer/.cargo/git/checkouts/teaclave-sgx-sdk-be25c2ad2f03718d/fdc2ea9/sgx_ucrypto/src/util.rs:79:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'already borrowed: BorrowMutError', /rustc/e82734e56b2a50d38e0937d08f559d15dbe8e46b/src/libcore/cell.rs:878:9
stack backtrace:
   0:     0x55cce114d634 - backtrace::backtrace::libunwind::trace::he392e7f3190d39cb
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x55cce114d634 - backtrace::backtrace::trace_unsynchronized::h6dce47f25b374263
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x55cce114d634 - std::sys_common::backtrace::_print_fmt::heee0ad6502408912
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55cce114d634 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h74e69a0924964693
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55cce117539c - core::fmt::write::h8a9d34ce2fb2b006
                               at src/libcore/fmt/mod.rs:1069
   5:     0x55cce1146fc3 - std::io::Write::write_fmt::h0f9fe59759aa4586
                               at src/libstd/io/mod.rs:1504
   6:     0x55cce114fe15 - std::sys_common::backtrace::_print::h3cf02f93364030ac
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55cce114fe15 - std::sys_common::backtrace::print::hf647a928a22b922a
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55cce114fe15 - std::panicking::default_hook::{{closure}}::he87f3d294472900e
                               at src/libstd/panicking.rs:198
   9:     0x55cce114fb52 - std::panicking::default_hook::h5a38802aba5b8783
                               at src/libstd/panicking.rs:218
  10:     0x55cce1150472 - std::panicking::rust_panic_with_hook::h67ec5890687fb40f
                               at src/libstd/panicking.rs:511
  11:     0x55cce115005b - rust_begin_unwind
                               at src/libstd/panicking.rs:419
  12:     0x55cce1173b11 - core::panicking::panic_fmt::hc45bcde77dfd550f
                               at src/libcore/panicking.rs:111
  13:     0x55cce1173933 - core::option::expect_none_failed::h2829177dcebf7924
                               at src/libcore/option.rs:1268
  14:     0x55cce0ed3e2a - <sgx_ucrypto::crypto::SgxRsaPubKey as core::ops::drop::Drop>::drop::h7be65ea9591bd068
  15:     0x55cce0ed38f7 - sgx_crypto_helper::rsa3072::Rsa3072PubKey::encrypt_buffer::h7e785e226fe7386d
  16:     0x55cce0e540c1 - encointer_client_teeproxy::perform_trusted_operation::h041aac8d063fd12b
  17:     0x55cce0e5091f - core::ops::function::Fn::call::h3c212c672d9be420
  18:     0x55cce0f6788f - substratee_stf::cli::cmd::{{closure}}::h00c4da31c14f4835
  19:     0x55cce0f63d30 - <clap_nested::Command<T> as clap_nested::CommandLike<T>>::run::h62019a3b5acf988b
  20:     0x55cce0e606dd - <clap_nested::MultiCommand<S,T> as clap_nested::CommandLike<S>>::run::h43db1dc6bb785b5a
  21:     0x55cce0e5a267 - clap_nested::Commander<(),T>::run::h11d00f7d4df35aed
  22:     0x55cce0e52d2f - encointer_client_teeproxy::main::h471ef99e4f4b8b51
  23:     0x55cce0e9b3c3 - std::rt::lang_start::{{closure}}::h8e7d3545cdb103ac
  24:     0x55cce1150988 - std::rt::lang_start_internal::{{closure}}::h14f855013a0a9b82
                               at src/libstd/rt.rs:52
  25:     0x55cce1150988 - std::panicking::try::do_call::hd06b1fb2148153ca
                               at src/libstd/panicking.rs:331
  26:     0x55cce1150988 - std::panicking::try::hc5084c9fed93c3ea
                               at src/libstd/panicking.rs:274
  27:     0x55cce1150988 - std::panic::catch_unwind::h65b7c253acc3466a
                               at src/libstd/panic.rs:394
  28:     0x55cce1150988 - std::rt::lang_start_internal::hbb65142b481b0e97
                               at src/libstd/rt.rs:51
  29:     0x55cce0e58242 - main
  30:     0x7f985dc50b97 - __libc_start_main
  31:     0x55cce0e3d1ea - _start
  32:                0x0 - <unknown>
thread panicked while panicking. aborting.
Illegal instruction (core dumped)
```

**Comment by brenzi** [comment]
it fails ar sgx_ucrypto:
https://github.com/apache/incubator-teaclave-sgx-sdk/blob/8f065be7a442157bf16dc7106feb795ea1c578eb/sgx_ucrypto/src/util.rs#L79

**Comment by brenzi** [comment]
This was run on a Intel(R) Pentium(R) CPU G850 @ 2.90GHz
```
cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 42
model name	: Intel(R) Pentium(R) CPU G850 @ 2.90GHz
stepping	: 7
microcode	: 0x2f
cpu MHz		: 2893.541
cache size	: 3072 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt tsc_deadline_timer xsave lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm arat pln pts md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 5787.07
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 42
model name	: Intel(R) Pentium(R) CPU G850 @ 2.90GHz
stepping	: 7
microcode	: 0x2f
cpu MHz		: 2893.538
cache size	: 3072 KB
physical id	: 0
siblings	: 2
core id		: 1
cpu cores	: 2
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt tsc_deadline_timer xsave lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm arat pln pts md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 5787.07
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

```

The RDRAND flag is missing, so this error is caused by using a HW without HW random support which sgx_ucrypto requires

**Comment by brenzi** [comment]
only chance is to change the dependency....won't fix!
